# exercise 1.1

In [ ]:
def string_with_unique_characters(s):
    d = {}
    for x in s:
        d[x] = 1
    return len(d) == len(s)
def string_with_unique_characters_2(s):
    c = 0
    for i, x in enumerate(s):
        for j, y in enumerate(s):
            if x == y and i != j:
                c += 1
    return c == 0

In [19]:
print string_with_unique_characters('massil')
print string_with_unique_characters('masil')
print string_with_unique_characters_2('massil')
print string_with_unique_characters_2('masil')

False
True
False
True


# exercise 1.2

In [27]:
def reverse_string(s):
    return s[::-1]
def reverse_string_2(s):
    s_reverse = ''
    for x in s:
        s_reverse = x + s_reverse
    return s_reverse

In [28]:
print reverse_string('massil')
print reverse_string_2('massil')

lissam
lissam


# exercise 1.3

In [37]:
def remove_duplicate_char(s):
    s = list(s)
    for i, x in enumerate(s):
        for j, y in enumerate(s):
            if x == y and i != j:
                s.pop(j)
    return s

In [38]:
remove_duplicate_char('massil')

['m', 'a', 's', 'i', 'l']

# exercise 1.4

In [4]:
def are_they_anagram(s1, s2):
    if len(s1) != len(s2):
        return False
    else:
        s2 = list(s2)
        for x in s1:
            for j, y in enumerate(s2):
                if x == y:
                    s2.pop(j)
        return s2 == []

In [6]:
print are_they_anagram('massil', 'masil')
print are_they_anagram('massil', 'silmas')

False
True


# exercise 1.5

In [10]:
def replace_spaces(s):
    s = list(s)
    for i, x in enumerate(s):
        if x == ' ': s[i] = '%20'
    return ''.join(s)

In [11]:
print replace_spaces('massil achab')
print replace_spaces(' je suis la ')

massil%20achab
%20je%20suis%20la%20


# exercise 1.6

In [7]:
def rotate(A):
    n = len(A)
    for layer in range(n/2):
        first = layer
        last = n-1-layer
        for i in range(first, last):
            offset = i - first
            top = A[first][i]
            # left -> top
            A[first][i] = A[last-offset][first]
            # bottom -> left
            A[last-offset][first] = A[last][last-offset]
            # right -> bottom
            A[last][last-offset] = A[i][last]
            # top -> right
            A[i][last] = top

In [9]:
A = np.arange(25).reshape(5,5)
print A
rotate(A)
print A

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[20 15 10  5  0]
 [21 16 11  6  1]
 [22 17 12  7  2]
 [23 18 13  8  3]
 [24 19 14  9  4]]


# exercise 1.7

In [13]:
def fill_row_column(A):
    m = len(A)
    n = len(A[0])
    def find_zeros(B):
        rows = []
        cols = []
        for i, X in enumerate(B):
            for j, x in enumerate(X):
                if x == 0:
                    if i not in rows: rows.append(i)
                    if j not in cols: cols.append(j)
        return rows, cols
    rows, cols = find_zeros(A)
    for i in rows:
        A[i] = [0] * n
    for j in cols:
        for i in range(m):
            A[i, j] = 0

In [18]:
A = np.arange(60).reshape(6,10)
A[3][5] = 0
print A
fill_row_column(A)
print A

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34  0 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]]
[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0 11 12 13 14  0 16 17 18 19]
 [ 0 21 22 23 24  0 26 27 28 29]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0 41 42 43 44  0 46 47 48 49]
 [ 0 51 52 53 54  0 56 57 58 59]]


# exercise 1.8

In [21]:
def isSubstring(s1, s2):
    if len(s1) > len(s2):
        return s2 in s1
    else:
        return s1 in s2
def is_rotation(s1, s2):
    if len(s1) != len(s2):
        return False
    else:
        return isSubstring(s2,s1+s1)

In [24]:
print is_rotation('waterbottle', 'erbottlewat')

True
